owner: ivy-digital # GitHub username
repo: gsm-upptime # GitHub repository name
user-agent: smart-assistant

sites:
  - name: GSM API AZURE
    url: $GSM_API_URL
  - name: s t a - r i o - c l a r o
    url: $STA_RIOCLARO_URL
  - name: s t a - t e r e z a
    url: $STA_TEREZA_URL
  - name: s a s s o m
    url: $SASSOM_URL
  - name: a l t e r
    url: $ALTER_URL
  - name: a b a s
    url: $ABAS_URL
  - name: h s a ú d e
    url: $HSAUDE_URL
  - name: s t a - i t a p e v a
    url: $STA_ITAPEVA_URL
  - name: m a i s s a ú d e
    url: $MAIS_SAUDE_URL
  - name: a m h a
    url: $AMHA_URL
  - name: i n t e r m e d i c i
    url: $INTERMEDICI_URL
  - name: S E R M E D - O D O N T O
    method: POST
    url: $SERMED_ODONTO_URL
    headers:
      - "Content-Type: application/json"
    body: '{"userId":"","accessKey":"","GrantType":"password"}'  
    
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /gsm-upptime
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Guia Saúde + | Status
  logoUrl: https://raw.githubusercontent.com/ivy-digital/gsm-upptime/master/assets/logoGuiaSaude.jpeg
  theme: light

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
