owner: smart-assistant # GitHub username
repo: gsm-upptime # GitHub repository name
user-agent: smart-assistant

sites:
  - name: sta-rioclaro
    url: https://santacasasauderc.com.br/agsi-restful/api/credenciados/1
  - name: sta-tereza
    url: http://200.170.153.217:9091/agsi-restful/api/credenciados/1
  - name: sassom
    url: http://portal.sassom.com.br/agsi-restful-teste/api/credenciados/1
  - name: alter
    url: https://agsi.alteronline.com.br:8443/agsi-restful/api/credenciados/0
  - name: abas
    url: http://52.67.80.50:8080/agsi-restful/api/credenciados/1
  - name: hsaude
    url: http://agsi-restful.hsaude.com.br/agsi-restful/api/credenciados/0
  - name: sta-itapeva
    url: http://200.232.157.44:8081/agsi-restful/api/credenciados/1
  - name: maissaude
    url: http://200.146.238.201:8081/agsi-restful/api/credenciados/1
  - name: amha
    url: http://novoatibaia.bluesolutions.com.br:8080/agsi-restful/api/credenciados/1
  - name: intermedici
    url: http://datacenter.agsisistemas.com.br:8080/intermedici-agsi-restful/api/credenciados/1

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /gsm-upptime
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Guia Saúde + | Status
  logoUrl: /assets/logoGuiaSaude.jpeg
  theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
